### ISSUE TITLE
Need Use Cases

### ISSUE THREAD

**Issue by bgulla** [clemenko/cosigning_carbide#1]
Looks good but missing some impactful opportunities. 

* Add an example of how to use SBOMs to detect vulnerable libraries in an image. Example (would rather not use addl tools like `grype` if possible: https://anchore.com/log4j/how-to-find-and-fix-log4j-with-open-source-enterprise-tools-anchore/ 
* Enforcement: Having the digital signatures is one thing, using them is another. Please build a use-case how to enforce digital signature checking of Rancher images. Use kubewarden, dont go down the route of how to install, just link the docs. see: https://rancherfederal.github.io/carbide-docs/docs/registry-docs/enforcement

**Comment by clemenko** [comment]
The use case I was looking at is how to air gap all the bits. But ran into a wall since `cosign` doesn't support it.  

Do you think adding extra tools like `grype` and `kubewarden` are going to weigh down the audience? 

I was thinking building the supply chain across the air gap with verification at each gate would simplify the OPA enforcement story.

thoughts?

**Comment by clemenko** [comment]
Who is the target audience? 
I am aiming at new k8s practitioners.

**Comment by clemenko** [comment]
@bgulla thoughts? Who is the target audience?

**Comment by clemenko** [comment]
@bgulla take a look. I went a little higher.

**Comment by clemenko** [comment]
Closed are per administrative conversation.
